
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://karmahostage.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /ethicalhackernotebook

# Google tracking id to track your visitors

google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "KarmaHostage"
title: "Ethical Hacker's Notebook"
description: "The notebook by hackers, for hackers."
keywords: "ethical, hacking"
favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: False
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Where’s your will to be weird?"

me-img: "/img/jetpacktocat.png"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "KarmaHostage"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "quintendeswaef@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "twitter"
    url: "https://twitter.com/QuintenDes"
  - title: "github"
    url: "https://github.com/KarmaHostage/EthicalHackerNotebook"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  #Learn: 'learn'
  #About: 'about'
  #Blog: 'latest-post'
  #Timeline: 'timeline'
  #Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji

# cyber security subjects, add to these if you want to add a feature on the website

karmahostage:
  subjects:
    - name: "Tools"
      md-file: "README.md"
      title: "Tools"
      icon: "cog"
      url: "tools"
    - name: "Cryptography"
      md-file: "cryptography/README.md"
      title: "Cryptography"
      icon: "lock"
      url: "cryptography"
    - name: "Wireless"
      md-file: "wireless_security/README.md"
      title: "Wireless Security"
      icon: "wifi"
      url: "wirless-security"
    - name: "MITM Attacks"
      md-file: "mitm_attacks/README.md"
      title: "MitM Attacks"
      icon: "cog"
      url: "mitm-attacks"
    - name: "Reconnaissance"
      md-file: "reconnaissance/README.md"
      title: "Reconnaissance"
      icon: "cog"
      url: "reconnaissance"
    - name: "Enumeration"
      md-file: "enumeration/README.md"
      title: "Enumeration"
      icon: "cog"
      url: "enumeration"
    - name: "Exploitation"
      md-file: "exploitation/README.md"
      title: "Exploitation"
      icon: "cog"
      url: "exploitation"
    - name: "Web Application Security"
      md-file: "web_application_security/README.md"
      title: "WebApp Security"
      icon: "cog"
      url: "web_application_security"
    - name: "Password Security"
      md-file: "password_security/README.md"
      title: "Password Security"
      icon: "cog"
      url: "password-security"
